Repository AlgorithmStudy23/Algorithm, pull requests merged in 2023-08, with the labels that each got.

#30 황유연: 베스트앨범(23.08.01)
  week2/베스트앨범/황유연_베스트앨범.py
Labels: 완료

#31 황유연: 틱택토 풀이 수정(23.08.01)
  week1/틱택토/틱택토.py
Labels: 완료

#32 황유연: 양과 늑대 추가(23.08.01)
  week1/양과늑대/황유연_양과늑대.py
Labels: 완료

#34 황승혜:후보키(23.08.02)
  README.md
  week2/베스트앨범/황승혜_베스트앨범.cpp
  week2/후보키/황승혜_후보키.cpp
Labels: 진행중, 다시 풀어볼 문제

#38 Yooyeon
  week2/후보키/황유연_후보기.py
Labels: 완료

#39 황유연: 후보키 풀이 수정(23.08.02)
  week2/후보키/황유연_후보키.py
Labels: 완료

#41 Heesu
  week2/상담원_인원/신희수_상담원_인원.py
Labels: 진행중, 다시 풀어볼 문제

#42 황승혜:상담원 인원
  week2/상담원_인원/황승혜_상담원_인원.cpp
Labels: 진행중, 다시 풀어볼 문제

#49 Heesu
  week2/자석/신희수_자석.py
  week3/알고스팟/신희수_알고스팟.py
Labels: 완료

#51 Yooyeon
  week3/알고스팟/황유연_알고스팟.py
Labels: 완료

#53 황유연: 상담원 인원 수정 (23.08.07)
  week2/상담원_인원/황유연_상담원_인원.py
Labels: 완료, 다시 풀어볼 문제

#55 황유연: 미로탈출명령어 (23.08.08)
  week3/미로_탈출_명령어/황유연_미로_탈출_명령어.py
Labels: 진행중

#59 황유연: 최단경로(23.08.09)
  week3/최단경로/황유연_최단경로.py
Labels: 완료

#60 황승혜:최단경로(23.08.09)
  week3/최단경로/황승혜_최단경로.cpp
Labels: 완료

#69 Yooyeon
  week3/게임_개발/황유연_게임_개발.py
  week3/경주로_건설/황유연_경주로_건설.py
  week3/뉴스_전하기/황유연_뉴스_전하기.py
  week3/성격_유형_검사하기/황유연_성격_유형_검사하기.py
  week4/타임머신/황유연_타임머신.py
Labels: 진행중

#72 황유연: 상범 빌딩 (23.08.16)
  week4/상범_빌딩/황유연_상범_빌딩.py
Labels: 완료, BFS

#73 Seunghye
  week3/경주로_건설/황승혜_경주로_건설.cpp
  week4/상범빌딩/황승혜_상범빌딩.cpp
  week4/타임머신/황승혜_타임머신.cpp
Labels: 다시 풀어볼 문제, BFS

#76 황승혜:우주신과의 교감(23.08.17)
  week4/우주신과의_교감/황승혜_우주신과의_교감.cpp
Labels: 다시 풀어볼 문제, 그래프, 유니온파인드

#77 황유연: 우주신과의 교감(23.08.17)
  week4/우주신과의_교감/황유연_우주신과의_교감.py
Labels: 진행중, BFS

#80 Yooyeon
  week4/전력망을_둘로_나누기/황유연_전력망을_둘로_나누기.py
  week4/증가하는_수/황유연_증가하는_수.py
  week4/플로이드/황유연_플로이드.py
  week5/자석/황유연_자석.py
Labels: 완료

#83 황유연: 우주신과의 교감(23.08.22)
  week5/우주신과의_교감/황유연_우주신과의_교감.py
Labels: 완료, 다시 풀어볼 문제, 유니온파인드

#84 황승혜:자석(23.08.22)
  week2/소수_찾기/황승혜_소수_찾기.cpp
  week4/전력망_둘로_나누기/황승혜_전력망_둘로_나누기.cpp
  week4/플로이드/황승혜_플로이드.cpp
  week5/소수_찾기/황승혜_소수_찾기.cpp
  week5/자석/황승혜_자석.cpp
Labels: 완료, 구현, 투포인터

#88 Yooyeon
  week5/뉴스_전하기/황유연_뉴스_전하기.py
Labels: 완료, 트리

#89 황유연: 미로 탈출 명령어 (23.08.23)
  week5/미로_탈출_명령어/황유연_미로_탈출_명령어.py
Labels: 완료, BFS
