Repository AlgorithmStudy23/Algorithm, pull requests merged in 2023-07, with the labels that each got.

#7 황승혜:암호코드(23.07.26)
  week1/암호코드/황승혜_암호코드.cpp
Labels: 완료

#9 신희수:암호코드(23.07.26)
  week1/암호코드/신희수_암호코드
Labels: 완료

#12 황승혜:가르침(23.07.27)
  week1/가르침/황승혜_가르침.cpp
  week1/암호코드/황유연_암호코드.py
Labels: 진행중, 다시 풀어볼 문제

#14 황유연: 가르침(23.07.27)
  week1/가르침/황유연_가르침.py
Labels: 진행중, 다시 풀어볼 문제

#15 황유연: 가르침 문제풀이 수정(23.07.27)
  week1/가르침/황유연_가르침.py
Labels: 완료

#17 황유연: 소수 구하기, 사이클 게임 문제풀이 (23.07.28)
  week1/사이클_게임/사이클_게임.py
  week1/소수_구하기/황유연_소수_구하기.py
Labels: 완료

#18 황유연: 틱택토 문제풀이(23.07.28)
  week1/틱택토/틱택토.py
Labels: 진행중

#20 Seunghye
  week1/사이클 게임/황승혜_사이클게임.cpp
  week1/소수 구하기/황승혜_소수구하기.cpp
  week1/암호코드/황승혜_암호코드.cpp
  week1/양과 늑대/양과 늑대.cpp
  week1/틱택토/틱택토.cpp
Labels: 진행중, 다시 풀어볼 문제

#21 신희수
  week1/소수구하기/신희수_소수구하기.py
  week1/틱택토/신희수_틱택토.py
Labels: 진행중, 다시 풀어볼 문제

#26 황승혜 : 징검다리 건너기
  week2/징검다리_건너기/황승혜_징검다리_건너기.cpp
Labels: 완료
